existingSecret: pgadmin-secret

env:
  existingSecret: pgadmin-secret
  email: chart@domain.com

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: pgadmin.delavande.fr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: pgadmin-tls
      hosts:
        - pgadmin.delavande.fr

service:
  type: ClusterIP
  port: 80
